// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQgfigksPW8daKXNce-WGD_vzycHHUEs',
    appId: '1:590473724301:web:c4c1bcaec62b75c6307dc4',
    messagingSenderId: '590473724301',
    projectId: 'gohelp-6f9ef',
    authDomain: 'gohelp-6f9ef.firebaseapp.com',
    storageBucket: 'gohelp-6f9ef.appspot.com',
    measurementId: 'G-5PJC46HWM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnshlSO6yftsB_GhyYffSs4Iq21g6y-cg',
    appId: '1:590473724301:android:b75e4d555d83a87b307dc4',
    messagingSenderId: '590473724301',
    projectId: 'gohelp-6f9ef',
    storageBucket: 'gohelp-6f9ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-xNwXax7nzrBsqtjp1V8bUTJuZ_eiIS4',
    appId: '1:590473724301:ios:c4ac1724d7ba93dd307dc4',
    messagingSenderId: '590473724301',
    projectId: 'gohelp-6f9ef',
    storageBucket: 'gohelp-6f9ef.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-xNwXax7nzrBsqtjp1V8bUTJuZ_eiIS4',
    appId: '1:590473724301:ios:c4ac1724d7ba93dd307dc4',
    messagingSenderId: '590473724301',
    projectId: 'gohelp-6f9ef',
    storageBucket: 'gohelp-6f9ef.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );
}
